\i sql/migrations/001_extensions_and_users.sql
\i sql/migrations/002_products.sql
\i sql/migrations/003_qr_batches_and_codes.sql
\i sql/migrations/004_ledger_transactions.sql
\i sql/migrations/005_payouts.sql
\i sql/migrations/006_auth_and_documents.sql
\i sql/migrations/007_qr_batch_label_style.sql
\i sql/migrations/008_product_description_color.sql
\i sql/migrations/009_refresh_token_revoked_at.sql
\i sql/migrations/010_device_tokens_and_sessions.sql
