\i sql/migrations/001_extensions_and_users.sql
\i sql/migrations/002_products.sql
\i sql/migrations/003_qr_batches_and_codes.sql
\i sql/migrations/004_ledger_transactions.sql
\i sql/migrations/005_payouts.sql
\i sql/migrations/006_auth_and_documents.sql
\i sql/migrations/007_qr_batch_label_style.sql
\i sql/migrations/008_product_description_color.sql
\i sql/migrations/009_refresh_token_revoked_at.sql
\i sql/migrations/010_device_tokens_and_sessions.sql
\i sql/migrations/011_qr_batch_coupon_name.sql
\i sql/migrations/012_user_profile_fields.sql
\i sql/migrations/013_reward_store.sql
\i sql/migrations/014_activity_feed_indexes.sql
\i sql/migrations/015_reward_catalog_status.sql
\i sql/migrations/016_reward_redemption_status.sql
\i sql/migrations/017_campaigns.sql
\i sql/migrations/018_partner_approval_status.sql
\i sql/migrations/019_notifications.sql
\i sql/migrations/020_notification_broadcast_fields.sql
